[package]
name = "base-64-decoder-opener"
version = "0.1.0"
authors = ["Shardul Vaidya <cam.v737@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "1"
base64 = "0.12.3"
regex = "1"